function(f mandatory1 mandatory2)
  message("mandatory1=${mandatory1}, mandatory2=${mandatory2}")
  message("ARGC=${ARGC}")
  message("ARGV=${ARGV}")
  message("ARGN=${ARGN}")
  list(APPEND argn "${ARGN}")

  foreach(arg IN LISTS ARGN)
    message("arg= ${arg}")
  endforeach()

  foreach(arg IN LISTS argn)
    message("arg2= ${arg}")
  endforeach()
endfunction()

function(read_semver)
  # set(prefix, ARG)
  set(options SPLIT DEBUG_INFO)
  set(oneValueArgs OUTPUT_VARIABLE_NAME FILE_NAME)
  set(multiValueArgs "")
  cmake_parse_arguments(ARG "${options}" "${oneValueArgs}" "${multiValueArgs}"
                        ${ARGN})
  if(ARG_DEBUG_INFO)
    message("arg_debug_info :${ARG_DEBUG_INFO}")
    message("arg_split :${ARG_SPLIT}")
  endif()
endfunction()
